version: '3.8'

services:
  postgres_db:
    image: postgres:16
    environment:
      POSTGRES_USER: laguna_diego
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: laguna_diego_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
